[build]
  command = "npm run update:bookshelf; npm run build"
  publish = "dist"

[env.production]
  # Add a longer timeout for the build to accommodate API requests
  NODE_OPTIONS = "--max-old-space-size=4096"
